groups:
  - name: web_unhealth
    rules:
      - alert: web_unhealth
        expr: probe_http_status_code{instance=~".*"} == 0
        for: 1m
        labels:
          role: web
          type: stability
        annotations:
          summary: "web is out of service"
          description: "{{ $labels.instance }} has out of service for 1m."
          username: "@channel"
  - name: web_gets_many_requests
    rules:
      - alert: web_gets_many_requests
        expr: sum by (instance) (rate (flask_http_request_total{job=~".*-web"} [1m])) > 5
        for: 1m
        labels:
          role: web
          type: stability
        annotations:
          summary: "too many request sent to web"
          description: "{{ $labels.instance }} has over 5 RPS for 1m."
          username: "@channel"

