groups:
  - name: blackbox_for_website
    rules:
      - alert: web_down
        expr: |
          max by (instance) (probe_http_status_code)
          == 0
        for: 1m
        labels:
          type: stability
          severity: critical
        annotations:
          summary: "web is down"
          description: "{{ $labels.instance }} is down for 1m."

  - name: http_requests
    rules:
      - alert: http_5xx_rate_high
        expr: |
          sum by (instance) (rate(http_requests_total{status=~"5XX"} [2m]))
          / sum by (instance) (rate(http_requests_total{status=~".*"} [2m]))
          > 0.05
        for: 1m
        labels:
          type: stability
          severity: critical
        annotations:
          summary: "HTTP 5xx rate is high"
          description: "{{ $labels.instance }} produces HTTP_5xx rate > 5% within 1m."

      - alert: http_request_rate_high
        expr: |
          sum by (instance) (rate (http_requests_total{} [2m]))
          > 1
        for: 1m
        labels:
          type: stability
          severity: warning
        annotations:
          summary: "HTTP requests rate is high"
          description: "{{ $labels.instance }} gets request > 1 RPS within 1m."
