modules:
  http_2xx_with_ipv4:
    prober: http
    timeout: 10s
    http:
      method: GET
      preferred_ip_protocol: "ip4"

  http_2xx_with_ipv4_no_ssl:
    prober: http
    timeout: 10s
    http:
      method: GET
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: true
