global:
  resolve_timeout: 3m

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: "slack_000"
  routes:
    - receiver: slack_100
      group_by: ["alertname", "type"]
      match:
        type: performance

receivers:
  - name: "slack_000"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#monitoring"
        send_resolved: true
        color: '{{ template "slack.color" . }}'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
  - name: "slack_100"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#monitoring"
        send_resolved: true
        color: '{{ template "slack.color" . }}'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'
