global:
  resolve_timeout: 3m

route:
  group_by: ["alertname"]
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 1m
  receiver: "slack_000"
  routes:
    - receiver: slack_100
      group_by: ["alertname", "type"]
      match:
        type: performance

receivers:
  - name: "slack_000"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#monitoring"
        text: 'rule #000: {{ if eq .Status "firing" }} Critical!! {{ else }} Safety!! {{ end }} {{ .CommonAnnotations.description }}'
        title: "{{.CommonAnnotations.summary}}"
        send_resolved: true
  - name: "slack_100"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#monitoring"
        text: 'rule #100: {{ if eq .Status "firing" }} Critical!! {{ else }} Safety!! {{ end }} {{ .CommonAnnotations.description }}'
        title: "{{.CommonAnnotations.summary}}"
        send_resolved: true

